version: '3.9'
services:
  db:
    image: 'postgres:16'
    container_name: 'db'
    environment:
      - 'POSTGRES_PASSWORD=password'
      - 'POSTGRES_USER=user'
      - 'POSTGRES_DB=db'
      - 'TZ=Asia/Tokyo'
    volumes:
      - './data:/var/lib/postgresql/data'
    ports:
      - '5432:5432'
  adminer:
    image: 'adminer'
    container_name: 'adminer'
    ports:
      - '49152:8080'
